apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminclus-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: adminclus-clusrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: adminclus-clusrolebinding
subjects:
- kind: ServiceAccount
  name: adminclus-sa
  namespace: action
roleRef:
  kind: ClusterRole
  name: adminclus-clusrole
  apiGroup: rbac.authorization.k8s.io
---