apiVersion: v1
kind: ServiceAccount
metadata:
  name: adminnsnosecret-sa
  namespace: action
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: action
  name: adminnsnosecret-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: [""]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: adminnsnosecret-rolebinding
  namespace: action
subjects:
- kind: ServiceAccount
  name: adminnsnosecret-sa
  namespace: action
roleRef:
  kind: Role
  name: adminnsnosecret-role
  apiGroup: rbac.authorization.k8s.io
---