apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonlyns-sa
  namespace: action
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: action
  name: readonlyns-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonlyns-rolebinding
  namespace: action
subjects:
- kind: ServiceAccount
  name: readonlyns-sa
  namespace: action
roleRef:
  kind: Role
  name: readonlyns-role
  apiGroup: rbac.authorization.k8s.io
---